project_id = "dzzeaesctendsggfdxra"

[functions.admin-bans]
verify_jwt = false

[functions.user-messages]
verify_jwt = false

[functions.admin-messages]
verify_jwt = false

[functions.validate-guess]
verify_jwt = false

[functions.save-game-history]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.get-game-history]
verify_jwt = false

[functions.admin-check-role]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false