// Famous people data by country
export const countryFamousPeople: Record<string, string> = {
  'Afghanistan': 'Ahmad Shah Massoud',
  'Albania': 'Mother Teresa',
  'Algeria': 'Abdelaziz Bouteflika',
  'Andorra': 'Suzanne Perlman',
  'Angola': 'Agostinho Neto',
  'Antigua and Barbuda': 'Sir Vivian Richards',
  'Argentina': 'Lionel Messi',
  'Armenia': 'Charles Aznavour',
  'Australia': 'Chris Hemsworth',
  'Austria': 'Wolfgang Amadeus Mozart',
  'Azerbaijan': 'Heydar Aliyev',
  'Bahamas': 'Sidney Poitier',
  'Bahrain': 'Isa bin Salman Al Khalifa',
  'Bangladesh': 'Sheikh Mujibur Rahman',
  'Barbados': 'Rihanna',
  'Belarus': 'Marc Chagall',
  'Belgium': 'Jean-Claude Van Damme',
  'Belize': 'Dean Barrow',
  'Benin': 'Angélique Kidjo',
  'Bhutan': 'Jigme Khesar Namgyel Wangchuck',
  'Bolivia': 'Evo Morales',
  'Bosnia and Herzegovina': 'Goran Bregović',
  'Botswana': 'Seretse Khama',
  'Brazil': 'Pelé',
  'Brunei': 'Hassanal Bolkiah',
  'Bulgaria': 'Hristo Stoichkov',
  'Burkina Faso': 'Thomas Sankara',
  'Burundi': 'Melchior Ndadaye',
  'Cabo Verde': 'Cesária Évora',
  'Cambodia': 'King Norodom Sihanouk',
  'Cameroon': 'Roger Milla',
  'Canada': 'Justin Bieber',
  'Central African Republic': 'Barthélemy Boganda',
  'Chad': 'Idriss Déby',
  'Chile': 'Pablo Neruda',
  'China': 'Confucius',
  'Colombia': 'Shakira',
  'Comoros': 'Ahmed Abdallah',
  'Congo': 'Papa Wemba',
  'Costa Rica': 'Óscar Arias',
  'Croatia': 'Nikola Tesla',
  'Cuba': 'Fidel Castro',
  'Cyprus': 'Makarios III',
  'Czech Republic': 'Franz Kafka',
  'Czechia': 'Franz Kafka',
  'Denmark': 'Hans Christian Andersen',
  'Djibouti': 'Hassan Gouled Aptidon',
  'Dominica': 'Douglas Charles',
  'Dominican Republic': 'Juan Pablo Duarte',
  'Ecuador': 'Eloy Alfaro',
  'Egypt': 'Cleopatra',
  'El Salvador': 'Óscar Romero',
  'Equatorial Guinea': 'Teodoro Obiang',
  'Eritrea': 'Isaias Afwerki',
  'Estonia': 'Arvo Pärt',
  'Eswatini': 'King Mswati III',
  'Ethiopia': 'Haile Selassie',
  'Fiji': 'Ratu Sir Lala Sukuna',
  'Finland': 'Jean Sibelius',
  'France': 'Napoleon Bonaparte',
  'Gabon': 'Omar Bongo',
  'Gambia': 'Dawda Jawara',
  'Georgia': 'Joseph Stalin',
  'Germany': 'Albert Einstein',
  'Ghana': 'Kwame Nkrumah',
  'Greece': 'Aristotle',
  'Grenada': 'Maurice Bishop',
  'Guatemala': 'Rigoberta Menchú',
  'Guinea': 'Ahmed Sékou Touré',
  'Guinea-Bissau': 'Amílcar Cabral',
  'Guyana': 'Cheddi Jagan',
  'Haiti': 'Toussaint Louverture',
  'Honduras': 'Francisco Morazán',
  'Hungary': 'Ferenc Puskás',
  'Iceland': 'Björk',
  'India': 'Mahatma Gandhi',
  'Indonesia': 'Sukarno',
  'Iran': 'Cyrus the Great',
  'Iraq': 'Saddam Hussein',
  'Ireland': 'James Joyce',
  'Israel': 'Golda Meir',
  'Italy': 'Leonardo da Vinci',
  'Ivory Coast': 'Didier Drogba',
  'Jamaica': 'Bob Marley',
  'Japan': 'Hayao Miyazaki',
  'Jordan': 'King Hussein',
  'Kazakhstan': 'Abai Qunanbaiuly',
  'Kenya': 'Wangari Maathai',
  'Kiribati': 'Anote Tong',
  'North Korea': 'Kim Il-sung',
  'South Korea': 'BTS',
  'Kosovo': 'Rita Ora',
  'Kuwait': 'Sheikh Sabah Al-Ahmed',
  'Kyrgyzstan': 'Manas',
  'Laos': 'Kaysone Phomvihane',
  'Latvia': 'Rainis',
  'Lebanon': 'Fairuz',
  'Lesotho': 'Ntsu Mokhehle',
  'Liberia': 'Ellen Johnson Sirleaf',
  'Libya': 'Omar al-Mukhtar',
  'Liechtenstein': 'Prince Hans-Adam II',
  'Lithuania': 'Jonas Basanavičius',
  'Luxembourg': 'Jean, Grand Duke of Luxembourg',
  'Madagascar': 'Philibert Tsiranana',
  'Malawi': 'Hastings Banda',
  'Malaysia': 'Tunku Abdul Rahman',
  'Maldives': 'Mohamed Nasheed',
  'Mali': 'Modibo Keïta',
  'Malta': 'Dom Mintoff',
  'Marshall Islands': 'Amata Kabua',
  'Mauritania': 'Moktar Ould Daddah',
  'Mauritius': 'Sir Seewoosagur Ramgoolam',
  'Mexico': 'Benito Juárez',
  'Micronesia': 'John N. Usher',
  'Moldova': 'Stephen the Great',
  'Monaco': 'Prince Rainier III',
  'Mongolia': 'Genghis Khan',
  'Montenegro': 'Petar II Petrović-Njegoš',
  'Morocco': 'King Mohammed V',
  'Mozambique': 'Samora Machel',
  'Myanmar': 'Aung San',
  'Namibia': 'Sam Nujoma',
  'Nauru': 'Hammer DeRoburt',
  'Nepal': 'Tenzing Norgay',
  'Netherlands': 'Vincent van Gogh',
  'New Zealand': 'Sir Edmund Hillary',
  'Nicaragua': 'Augusto Sandino',
  'Niger': 'Hamani Diori',
  'Nigeria': 'Chinua Achebe',
  'North Macedonia': 'Mother Teresa',
  'Norway': 'Roald Amundsen',
  'Oman': 'Sultan Qaboos',
  'Pakistan': 'Muhammad Ali Jinnah',
  'Palau': 'Haruo Remeliik',
  'Panama': 'Mariano Rivera',
  'Papua New Guinea': 'Sir Michael Somare',
  'Paraguay': 'José Gaspar Rodríguez de Francia',
  'Peru': 'Mario Vargas Llosa',
  'Philippines': 'José Rizal',
  'Poland': 'Marie Curie',
  'Portugal': 'Vasco da Gama',
  'Qatar': 'Sheikh Tamim',
  'Romania': 'Nicolae Ceaușescu',
  'Russia': 'Peter the Great',
  'Rwanda': 'Paul Kagame',
  'Saint Kitts and Nevis': 'Sir Kennedy Simmonds',
  'Saint Lucia': 'Derek Walcott',
  'Saint Vincent and the Grenadines': 'Arthur Lewis',
  'Samoa': 'Malietoa Tanumafili II',
  'San Marino': 'Saint Marinus',
  'Sao Tome and Principe': 'Miguel Trovoada',
  'Saudi Arabia': 'King Abdulaziz',
  'Senegal': 'Léopold Sédar Senghor',
  'Serbia': 'Novak Djokovic',
  'Seychelles': 'France Albert René',
  'Sierra Leone': 'Milton Margai',
  'Singapore': 'Lee Kuan Yew',
  'Slovakia': 'Ľudovít Štúr',
  'Slovenia': 'France Prešeren',
  'Solomon Islands': 'Sir Peter Kenilorea',
  'Somalia': 'Ayaan Hirsi Ali',
  'South Africa': 'Nelson Mandela',
  'South Sudan': 'Salva Kiir',
  'Spain': 'Pablo Picasso',
  'Sri Lanka': 'Mahinda Rajapaksa',
  'Sudan': 'Ahmed al-Mirghani',
  'Suriname': 'Desi Bouterse',
  'Sweden': 'Alfred Nobel',
  'Switzerland': 'Roger Federer',
  'Syria': 'Nizar Qabbani',
  'Taiwan': 'Chiang Kai-shek',
  'Tajikistan': 'Rudaki',
  'Tanzania': 'Julius Nyerere',
  'Thailand': 'King Bhumibol Adulyadej',
  'Togo': 'Gnassingbé Eyadéma',
  'Tonga': 'King Tupou VI',
  'Trinidad and Tobago': 'Nicki Minaj',
  'Tunisia': 'Habib Bourguiba',
  'Turkey': 'Mustafa Kemal Atatürk',
  'Turkmenistan': 'Saparmurat Niyazov',
  'Tuvalu': 'Sir Kamuta Latasi',
  'Uganda': 'Idi Amin',
  'Ukraine': 'Taras Shevchenko',
  'United Arab Emirates': 'Sheikh Zayed',
  'United Kingdom': 'William Shakespeare',
  'United States': 'George Washington',
  'United States of America': 'George Washington',
  'Uruguay': 'José Artigas',
  'Uzbekistan': 'Amir Timur',
  'Vanuatu': 'Walter Lini',
  'Vatican City': 'Pope Francis',
  'Venezuela': 'Simón Bolívar',
  'Vietnam': 'Ho Chi Minh',
  'Yemen': 'Ali Abdullah Saleh',
  'Zambia': 'Kenneth Kaunda',
  'Zimbabwe': 'Robert Mugabe',
};

// Country to continent mapping
export const countryContinent: Record<string, string> = {
  // Africa
  'Algeria': 'Africa', 'Angola': 'Africa', 'Benin': 'Africa', 'Botswana': 'Africa',
  'Burkina Faso': 'Africa', 'Burundi': 'Africa', 'Cabo Verde': 'Africa', 'Cameroon': 'Africa',
  'Central African Republic': 'Africa', 'Chad': 'Africa', 'Comoros': 'Africa', 'Congo': 'Africa',
  'Djibouti': 'Africa', 'Egypt': 'Africa', 'Equatorial Guinea': 'Africa', 'Eritrea': 'Africa',
  'Eswatini': 'Africa', 'Ethiopia': 'Africa', 'Gabon': 'Africa', 'Gambia': 'Africa',
  'Ghana': 'Africa', 'Guinea': 'Africa', 'Guinea-Bissau': 'Africa', 'Ivory Coast': 'Africa',
  'Kenya': 'Africa', 'Lesotho': 'Africa', 'Liberia': 'Africa', 'Libya': 'Africa',
  'Madagascar': 'Africa', 'Malawi': 'Africa', 'Mali': 'Africa', 'Mauritania': 'Africa',
  'Mauritius': 'Africa', 'Morocco': 'Africa', 'Mozambique': 'Africa', 'Namibia': 'Africa',
  'Niger': 'Africa', 'Nigeria': 'Africa', 'Rwanda': 'Africa', 'Sao Tome and Principe': 'Africa',
  'Senegal': 'Africa', 'Seychelles': 'Africa', 'Sierra Leone': 'Africa', 'Somalia': 'Africa',
  'South Africa': 'Africa', 'South Sudan': 'Africa', 'Sudan': 'Africa', 'Tanzania': 'Africa',
  'Togo': 'Africa', 'Tunisia': 'Africa', 'Uganda': 'Africa', 'Zambia': 'Africa', 'Zimbabwe': 'Africa',
  
  // Asia
  'Afghanistan': 'Asia', 'Armenia': 'Asia', 'Azerbaijan': 'Asia', 'Bahrain': 'Asia',
  'Bangladesh': 'Asia', 'Bhutan': 'Asia', 'Brunei': 'Asia', 'Cambodia': 'Asia',
  'China': 'Asia', 'Georgia': 'Asia', 'India': 'Asia', 'Indonesia': 'Asia',
  'Iran': 'Asia', 'Iraq': 'Asia', 'Israel': 'Asia', 'Japan': 'Asia',
  'Jordan': 'Asia', 'Kazakhstan': 'Asia', 'Kuwait': 'Asia', 'Kyrgyzstan': 'Asia',
  'Laos': 'Asia', 'Lebanon': 'Asia', 'Malaysia': 'Asia', 'Maldives': 'Asia',
  'Mongolia': 'Asia', 'Myanmar': 'Asia', 'Nepal': 'Asia', 'North Korea': 'Asia',
  'Oman': 'Asia', 'Pakistan': 'Asia', 'Philippines': 'Asia', 'Qatar': 'Asia',
  'Saudi Arabia': 'Asia', 'Singapore': 'Asia', 'South Korea': 'Asia', 'Sri Lanka': 'Asia',
  'Syria': 'Asia', 'Taiwan': 'Asia', 'Tajikistan': 'Asia', 'Thailand': 'Asia',
  'Turkmenistan': 'Asia', 'United Arab Emirates': 'Asia', 'Uzbekistan': 'Asia',
  'Vietnam': 'Asia', 'Yemen': 'Asia',
  
  // Europe
  'Albania': 'Europe', 'Andorra': 'Europe', 'Austria': 'Europe', 'Belarus': 'Europe',
  'Belgium': 'Europe', 'Bosnia and Herzegovina': 'Europe', 'Bulgaria': 'Europe', 'Croatia': 'Europe',
  'Cyprus': 'Europe', 'Czech Republic': 'Europe', 'Czechia': 'Europe', 'Denmark': 'Europe',
  'Estonia': 'Europe', 'Finland': 'Europe', 'France': 'Europe', 'Germany': 'Europe',
  'Greece': 'Europe', 'Hungary': 'Europe', 'Iceland': 'Europe', 'Ireland': 'Europe',
  'Italy': 'Europe', 'Kosovo': 'Europe', 'Latvia': 'Europe', 'Liechtenstein': 'Europe',
  'Lithuania': 'Europe', 'Luxembourg': 'Europe', 'Malta': 'Europe', 'Moldova': 'Europe',
  'Monaco': 'Europe', 'Montenegro': 'Europe', 'Netherlands': 'Europe', 'North Macedonia': 'Europe',
  'Norway': 'Europe', 'Poland': 'Europe', 'Portugal': 'Europe', 'Romania': 'Europe',
  'Russia': 'Europe', 'San Marino': 'Europe', 'Serbia': 'Europe', 'Slovakia': 'Europe',
  'Slovenia': 'Europe', 'Spain': 'Europe', 'Sweden': 'Europe', 'Switzerland': 'Europe',
  'Turkey': 'Europe', 'Ukraine': 'Europe', 'United Kingdom': 'Europe', 'Vatican City': 'Europe',
  
  // North America
  'Antigua and Barbuda': 'North America', 'Bahamas': 'North America', 'Barbados': 'North America',
  'Belize': 'North America', 'Canada': 'North America', 'Costa Rica': 'North America',
  'Cuba': 'North America', 'Dominica': 'North America', 'Dominican Republic': 'North America',
  'El Salvador': 'North America', 'Grenada': 'North America', 'Guatemala': 'North America',
  'Haiti': 'North America', 'Honduras': 'North America', 'Jamaica': 'North America',
  'Mexico': 'North America', 'Nicaragua': 'North America', 'Panama': 'North America',
  'Saint Kitts and Nevis': 'North America', 'Saint Lucia': 'North America',
  'Saint Vincent and the Grenadines': 'North America', 'Trinidad and Tobago': 'North America',
  'United States': 'North America', 'United States of America': 'North America',
  
  // South America
  'Argentina': 'South America', 'Bolivia': 'South America', 'Brazil': 'South America',
  'Chile': 'South America', 'Colombia': 'South America', 'Ecuador': 'South America',
  'Guyana': 'South America', 'Paraguay': 'South America', 'Peru': 'South America',
  'Suriname': 'South America', 'Uruguay': 'South America', 'Venezuela': 'South America',
  
  // Oceania
  'Australia': 'Oceania', 'Fiji': 'Oceania', 'Kiribati': 'Oceania', 'Marshall Islands': 'Oceania',
  'Micronesia': 'Oceania', 'Nauru': 'Oceania', 'New Zealand': 'Oceania', 'Palau': 'Oceania',
  'Papua New Guinea': 'Oceania', 'Samoa': 'Oceania', 'Solomon Islands': 'Oceania',
  'Tonga': 'Oceania', 'Tuvalu': 'Oceania', 'Vanuatu': 'Oceania',
};

// Get famous person for a country
export const getFamousPerson = (country: string): string | null => {
  return countryFamousPeople[country] || null;
};

// Get continent for a country
export const getContinent = (country: string): string | null => {
  return countryContinent[country] || null;
};

// Get all countries
export const getAllCountries = (): string[] => {
  return Object.keys(countryFamousPeople);
};

// Get random country
export const getRandomCountry = (): string => {
  const countries = getAllCountries();
  return countries[Math.floor(Math.random() * countries.length)];
};
