// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzzeaesctendsggfdxra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6emVhZXNjdGVuZHNnZ2ZkeHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NjQxNDcsImV4cCI6MjA4MjI0MDE0N30.PwC5xpu-FNZfnSmNUAHhpuBG1UGZWR0emXo6MQrpEoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});